# Generated by Django 4.2.5 on 2023-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='Code',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='crypto',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='date',
            field=models.DateTimeField(default='2023-10-01 00:00:00'),
        ),
    ]
