# Generated by Django 4.2.5 on 2023-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_contactmodel_code_contactmodel_crypto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='date',
            field=models.CharField(default='00/00', max_length=5),
        ),
    ]
